In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train= pd.read_csv('train.csv')

In [3]:
train.head()

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,OH,107,area_code_415,no,yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,no
1,NJ,137,area_code_415,no,no,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,no
2,OH,84,area_code_408,yes,no,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,no
3,OK,75,area_code_415,yes,no,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,no
4,MA,121,area_code_510,no,yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,no

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   state                          4250 non-null   object
 1   account_length                 4250 non-null   int64
 2   area_code                      4250 non-null   object
 3   international_plan             4250 non-null   object
 4   voice_mail_plan                4250 non-null   object
 5   number_vmail_messages          4250 non-null   int64
 6   total_day_minutes              4250 non-null   float64
 7   total_day_calls                4250 non-null   int64
 8   total_day_charge               4250 non-null   float64
 9   total_eve_minutes              4250 non-null   float64
 10  total_eve_calls                4250 non-null   int64
 11  total_eve_charge               4250 non-null   float64
 12  total_night_minutes            4250 non-null   float64
 13  total_night_calls              4250 non-null   int64
 14  total_night_charge             4250 non-null   float64
 15  total_intl_minutes             4250 non-null   float64
 16  total_intl_calls               4250 non-null   int64
 17  total_intl_charge              4250 non-null   float64
 18  number_customer_service_calls  4250 non-null   int64
 19  churn                          4250 non-null   object
dtypes: float64(8), int64(7), object(5)
memory usage: 664.2+ KB

In [5]:
train['state']=train['state'].astype('category')
train.area_code= train.area_code.astype('category')

In [6]:
yes_binary= {'yes':'1','no': '0'}

In [7]:
train['international_plan']=train['international_plan'].map(yes_binary).astype('int64')
train['voice_mail_plan']=train['voice_mail_plan'].map(yes_binary).astype('int64')
train['churn']=train['churn'].map(yes_binary).astype('int64')

In [8]:
train_dummies= pd.get_dummies(train)

In [9]:
len(train_dummies.columns)

72

In [10]:
train_dummies.columns

Index(['account_length', 'international_plan', 'voice_mail_plan',
       'number_vmail_messages', 'total_day_minutes', 'total_day_calls',
       'total_day_charge', 'total_eve_minutes', 'total_eve_calls',
       'total_eve_charge', 'total_night_minutes', 'total_night_calls',
       'total_night_charge', 'total_intl_minutes', 'total_intl_calls',
       'total_intl_charge', 'number_customer_service_calls', 'churn',
       'state_AK', 'state_AL', 'state_AR', 'state_AZ', 'state_CA', 'state_CO',
       'state_CT', 'state_DC', 'state_DE', 'state_FL', 'state_GA', 'state_HI',
       'state_IA', 'state_ID', 'state_IL', 'state_IN', 'state_KS', 'state_KY',
       'state_LA', 'state_MA', 'state_MD', 'state_ME', 'state_MI', 'state_MN',
       'state_MO', 'state_MS', 'state_MT', 'state_NC', 'state_ND', 'state_NE',
       'state_NH', 'state_NJ', 'state_NM', 'state_NV', 'state_NY', 'state_OH',
       'state_OK', 'state_OR', 'state_PA', 'state_RI', 'state_SC', 'state_SD',
       'state_TN', 'state_TX', 'state_UT', 'state_VA', 'state_VT', 'state_WA',
       'state_WI', 'state_WV', 'state_WY', 'area_code_area_code_408',
       'area_code_area_code_415', 'area_code_area_code_510'],
      dtype='object')

In [11]:
shuffled= train_dummies.sample(frac=1).reset_index().drop('index',axis=1)

In [12]:
shuffled_scaled= (shuffled- shuffled.min())/(shuffled.max()-shuffled.min())

In [13]:
shuffled_scaled

,account_length,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,...,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,area_code_area_code_408,area_code_area_code_415,area_code_area_code_510
0,0.657025,0.0,0.0,0.000000,0.495875,0.636364,0.495817,0.476760,0.629412,0.476752,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.504132,1.0,0.0,0.000000,0.357041,0.642424,0.357095,0.358753,0.564706,0.358874,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.239669,0.0,0.0,0.000000,0.658321,0.563636,0.658300,0.467576,0.541176,0.467583,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.549587,0.0,0.0,0.000000,0.304410,0.884848,0.304384,0.612302,0.682353,0.612312,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.074380,0.0,0.0,0.000000,0.529445,0.593939,0.529451,0.707765,0.335294,0.707924,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,0.417355,0.0,1.0,0.923077,0.381223,0.503030,0.381191,0.652101,0.752941,0.652259,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4246,0.471074,0.0,0.0,0.000000,0.408535,0.818182,0.408467,0.773727,0.700000,0.773739,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4247,0.553719,0.0,1.0,0.538462,0.572973,0.606061,0.572959,0.686056,0.688235,0.685986,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4248,0.706612,0.0,0.0,0.000000,0.483073,0.745455,0.483099,0.509602,0.552941,0.509496,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4249,0.243802,0.0,0.0,0.000000,0.656330,0.400000,0.656292,0.460340,0.382353,0.460380,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [14]:
from sklearn.decomposition import PCA

In [15]:
pca= PCA(n_components=8)
pca.fit_transform(shuffled_scaled.drop('churn',axis=1))

array([[ 0.60200244, -0.30862684, -0.06769571, ...,  0.07608789,
         0.14212342, -0.0720074 ],
       [ 0.5993349 , -0.31589464, -0.03552761, ...,  0.27156796,
         0.37168666, -0.20681299],
       [ 0.61003163, -0.31646445, -0.06157966, ...,  0.09567393,
        -0.04517306, -0.28653664],
       ...,
       [-0.56019419,  0.72294532,  0.85560036, ..., -0.10577549,
        -0.23917751,  0.22710118],
       [-0.58678059, -0.39499588,  0.66483486, ...,  0.11814721,
        -0.09842709, -0.64006151],
       [-0.58548136, -0.3911958 ,  0.68200767, ...,  0.12952766,
        -0.25520662, -0.41609066]])

In [16]:
pca_data= pd.DataFrame(pca.components_,columns=shuffled_scaled.drop('churn',axis=1).columns,index= ['Pca1',
                                                                                         'Pca2',
                                                                                         'Pca3',
                                                                                         'Pca4',
                                                                                         'Pca5',
                                                                                         'Pca6',
                                                                                         'Pca7',
                                                                                         'Pca8'])

In [17]:
pca_data

,account_length,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,...,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,area_code_area_code_408,area_code_area_code_415,area_code_area_code_510
Pca1,-0.000244,-0.004836,0.028573,0.014944,0.007482,0.010340,0.007482,-0.005339,-0.001442,-0.005339,...,0.000949,0.003366,0.003559,-0.005621,-0.002101,-0.005769,0.003954,-0.425061,0.815342,-0.390281
Pca2,0.001174,-0.001856,0.855120,0.491270,-0.000755,-0.002386,-0.000757,0.004041,0.000889,0.004043,...,0.001756,-0.005726,-0.002366,-0.006789,0.003214,-0.005344,0.001206,0.124762,-0.022774,-0.101988
Pca3,-0.008335,0.023836,0.138409,0.079142,0.002223,-0.003077,0.002222,0.000870,-0.003317,0.000874,...,0.009524,-0.007971,0.005014,-0.004165,0.001066,0.006927,-0.003050,-0.684953,-0.024072,0.709026
Pca4,0.023350,0.993922,-0.003446,0.001675,0.046097,0.005190,0.046094,0.019935,-0.000747,0.019933,...,0.000094,-0.003976,0.003372,-0.005048,0.003289,-0.019977,0.012782,0.014908,0.003620,-0.018528
Pca5,-0.012745,-0.057996,-0.000978,0.004088,0.693525,-0.001357,0.693467,-0.054243,0.008233,-0.054250,...,0.040089,-0.018049,0.000043,0.000082,-0.011340,-0.016146,0.010202,0.005635,-0.008015,0.002380
Pca6,0.019506,0.029061,0.003468,0.004315,-0.041341,-0.010617,-0.041338,-0.674465,-0.002358,-0.674478,...,-0.002799,-0.009505,-0.030936,-0.007536,0.010899,0.186484,-0.018643,0.005481,-0.006502,0.001021
Pca7,0.002162,0.037921,0.002437,0.003925,-0.078415,0.003037,-0.078405,-0.113814,0.011693,-0.113811,...,-0.021355,0.023905,0.019856,0.017182,0.052784,-0.111769,-0.038933,-0.010876,0.010378,0.000498
Pca8,0.004463,-0.016145,0.007769,0.002485,0.017794,-0.006447,0.017788,-0.034804,-0.002135,-0.034803,...,0.085831,-0.000450,-0.050926,0.003126,0.033247,0.071358,0.019211,-0.007938,0.004025,0.003913

In [18]:
pca_Data=pca.fit_transform(shuffled_scaled.drop('churn',axis=1))

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [20]:
from sklearn.ensemble import BaggingClassifier , GradientBoostingClassifier, AdaBoostClassifier, RandomForestClassifier
import xgboost as xgb
from xgboost import XGBClassifier

In [21]:
X_train,X_test,y_train,y_test= train_test_split(pca_Data,shuffled_scaled[['churn']],test_size=0.25)

In [22]:
models = []
models.append(('KNN', KNeighborsClassifier()))
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('QDA', QuadraticDiscriminantAnalysis()))
models.append(('Tree', DecisionTreeClassifier()))
models.append(('svc', SVC()))
models.append(('BC', BaggingClassifier(base_estimator=LogisticRegression())))
models.append(('AB', AdaBoostClassifier(base_estimator=LogisticRegression())))
models.append(('GBM', GradientBoostingClassifier()))
models.append(('RF', RandomForestClassifier()))
models.append(('XGB', XGBClassifier()))

In [23]:
results= []
names= []
for name, model in models:
    cv_res= cross_val_score(model,X_train,y_train,cv=10,scoring='accuracy',n_jobs=-1)
    results.append(cv_res)
    names.append(name)
    res= '%s: %f. (%f)' %(name,cv_res.mean(),cv_res.std())
    print(res)

KNN: 0.898343. (0.013997)
LR: 0.860373. (0.013139)
LDA: 0.850650. (0.018835)
QDA: 0.855360. (0.022396)
Tree: 0.839037. (0.014817)
svc: 0.879203. (0.007487)
BC: 0.860373. (0.013435)
AB: 0.861627. (0.002859)
GBM: 0.896779. (0.010988)
RF: 0.900227. (0.009931)
XGB: 0.899598. (0.010441)

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
paremeters={ 'learning_rate':[0.1],
            'min_child_weight': [1],
            'max_depth': [9,12],
            'objective': ['binary:logistic'],
            'gamma': np.linspace(0.01,0.9,30)
    
}

In [26]:
grid_Search_xgb= GridSearchCV(estimator = XGBClassifier(use_label_encoder=False),param_grid=paremeters,
                             scoring='accuracy',cv= 10,n_jobs=-1)

results_xgb= grid_Search_xgb.fit(X_train,y_train)

[22:35:12] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [27]:
results_xgb.best_score_

0.9049368111827448

In [28]:
prediction_xgb=results_xgb.predict(X_test)

In [29]:
y_test

      churn
4083    0.0
1644    1.0
3449    0.0
2941    1.0
2203    0.0
...     ...
2175    0.0
79      0.0
1836    1.0
761     0.0
1929    0.0

[1063 rows x 1 columns]

In [30]:
(np.array(y_test[['churn']])== prediction_xgb).mean()

0.804745085927136